trigger:
  batch: true
  branches:
    include:
      - master
      - refs/tags/*
  paths:
    exclude:
    - '**/*.md'
    - '.appveyor.yml'
    - '.codecov.yml'
    - 'GitVersion.yml'
    - 'GitReleaseManager.yaml'
    - .vscode/*
    - .git*
    - .editorconfig
    - .nuke
    - LICENSE

pr:
  autoCancel: true
  branches:
    include:
      - master

resources:
  repositories:
    - repository: rsg
      type: github
      name: RocketSurgeonsGuild/AzureDevopsTemplates
      ref: refs/tags/v0.10.12
      endpoint: github

variables:
  - name: CONFIGURATION
    value: Release
  - name: VERBOSITY
    value: Normal
  - name: COVERAGE
    value: "$(Agent.BuildDirectory)/c"
  - name: ARTIFACTS
    value: $(Build.ArtifactStagingDirectory)
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: "true"
  - name: CodeCovToken
    value: 'ed1436a4-a776-4296-87e9-fe419e291c15'

jobs:
  - job: GitVersion
    pool:
      vmImage: "windows-2019"
    steps:
      - template: gitversion/store.yml@rsg
        parameters:
          NuGetVersion: "5.3.0"

  - job: Linux
    dependsOn:
      - GitVersion
      - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}:
          - GitHub_Draft_Release
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - template: nuke/job-steps.yml@rsg
        parameters:
          Configuration: $(Configuration)
          Verbosity: $(Verbosity)
          DotNetSdk:
            - "2.2.x"
            - "3.0.x"
          NuGetVersion: "5.3.0"
          Targets: "Default"
          Postfix: ''

  - ${{ if ne(variables['System.PullRequest.IsFork'], 'true') }}:
    - job: GitHub_Draft_Release
      pool:
        vmImage: "windows-2019"
      dependsOn:
        - GitVersion
      variables:
        - group: rsg-bot
      steps:
        # - checkout: none
        - template: gitversion/restore.yml@rsg
        - template: standard/github-draft-release.yml@rsg

    - job: Publish
      pool:
        vmImage: "windows-2019"
      dependsOn:
        - Linux
        - GitHub_Draft_Release
      steps:
        - download: current
          artifact: 'Nupkg'
        - template: standard/nuget-push.yml@rsg
          parameters:
            Artifacts: "$(Pipeline.Workspace)/Nupkg/"
            NuGetVersion: "5.3.0"
            Verbosity: $(Verbosity)
            GitHubPackages: true

    - job: GitHub_Release
      pool:
        vmImage: "windows-2019"
      dependsOn:
        - Linux
        - GitHub_Draft_Release
      variables:
        - group: rsg-bot
      steps:
        - template: gitversion/restore.yml@rsg
        - template: standard/github-release.yml@rsg
          parameters:
            DotNetSdk:
              - "2.2.x"
              - "3.0.x"
