trigger:
  branches:
    include:
      - master
      - refs/tags/*
pr:
  autoCancel: true
  branches:
    include:
      - master

resources:
  repositories:
    - repository: rsg
      type: github
      name: RocketSurgeonsGuild/AzureDevopsTemplates
      ref: refs/tags/v0.9.2
      endpoint: github

variables:
  - group: rsg-bot
  - name: CONFIGURATION
    value: Release
  - name: VERBOSITY
    value: Normal
  - name: COVERAGE
    value: "$(Agent.BuildDirectory)/c"
  - name: ARTIFACTS
    value: $(Build.ArtifactStagingDirectory)
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: "true"
  - name: CodeCovToken
    value: 'ed1436a4-a776-4296-87e9-fe419e291c15'

jobs:
  - job: GitVersion
    pool:
      vmImage: "windows-2019"
    steps:
      - template: gitversion/store.yml@rsg
        parameters:
          NuGetVersion: "5.2.0"

  - job: Linux
    dependsOn: GitVersion
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - template: nuke/job-steps.yml@rsg
        parameters:
          Configuration: $(Configuration)
          Verbosity: $(Verbosity)
          DotNet21Version: "2.1.x"
          DotNetVersion: "2.2.x"
          DotNet3Version: "3.0.100-rc1-014190"
          NuGetVersion: "5.2.0"
          Targets: "Default"
          Postfix: ''

  - ${{ if ne(variables['System.PullRequest.IsFork'], 'true') }}:
    - job: GitHub_Draft_Release
      pool:
        vmImage: "windows-2019"
      dependsOn:
        - GitVersion
      steps:
        # - checkout: none
        - template: gitversion/restore.yml@rsg
        - template: standard/github-draft-release.yml@rsg
          parameters:
            DotNet21Version: "2.1.x"
            DotNetVersion: "2.2.x"
            DotNet3Version: "3.0.100-rc1-014190"

    - job: Publish
      pool:
        vmImage: "windows-2019"
      dependsOn:
        - Linux
        - GitHub_Draft_Release
      steps:
        - download: current
          artifact: 'Nupkg'
        - template: standard/nuget-push.yml@rsg
          parameters:
            Artifacts: "$(Pipeline.Workspace)/Nupkg/"
            NuGetVersion: "5.2.0"
            Verbosity: $(Verbosity)
            GitHubPackages: false

    - job: GitHub_Release
      pool:
        vmImage: "windows-2019"
      dependsOn:
        - Linux
        - GitHub_Draft_Release
      steps:
        - template: gitversion/restore.yml@rsg
        - template: standard/github-release.yml@rsg
          parameters:
            DotNet21Version: "2.1.x"
            DotNetVersion: "2.2.x"
            DotNet3Version: "3.0.100-rc1-014190"
