trigger:
  branches:
    include:
      - master
      - refs/tags/*
pr:
  autoCancel: true
  branches:
    include:
      - master

resources:
  repositories:
    - repository: rsg
      type: github
      name: RocketSurgeonsGuild/AzureDevopsTemplates
      ref: refs/tags/v0.5.9
      endpoint: github

variables:
  Configuration: Release
  Verbosity: Normal
  DotNetVersion: "2.2.300"
  DotNet3Version: "3.0.100-preview6-012264"
  CakeVersion: "0.33.0"
  NuGetVersion: "5.1.0"
  Coverage: "$(Agent.BuildDirectory)/c"
  VstsCoverage: "$(Coverage)"
  Artifacts: $(Build.ArtifactStagingDirectory)
  VstsArtifacts: "$(Artifacts)"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"

jobs:
  - job: GitVersion
    pool:
      vmImage: "VS2017-Win2016"
    steps:
      - template: gitversion/store.yml@rsg
        parameters:
          NuGetVersion: $(NuGetVersion)

  - template: pipeline/cake-job.yml@rsg
    parameters:
      name: 'Linux'
      dependsOn: GitVersion
      vmImage: "Ubuntu-16.04"
      pushNuget: true
      Configuration: $(Configuration)
      Verbosity: $(Verbosity)
      CakeVersion: $(CakeVersion)
      DotNetVersion: $(DotNetVersion)
      DotNet3Version: $(DotNet3Version)
      NuGetVersion: $(NuGetVersion)
